name: Generate Snake Graph

on:
  push:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Graph
        uses: Platane/snk@v0.5.1
        with:
          github_user_name: VanessaJAvila
          # The following path will store the output files (replace YourUserName with your GitHub username)
          output_dir: ./generated-snake-graph

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update contribution graph snake"
          file_pattern: generated-snake-graph
          commit_options: '--no-verify'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
